server:
  port: 18888
spring:
  application:
    name: GATEWAY
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  routes:
    producer:
      path: /order/**
      serviceId: SERVICE-PRODUCER
    consumer:
      path: /share/**
      serviceId: SERVICE-CONSUMER
eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/


