server:
  port: 18888
spring:
  application:
    name: GATEWAY
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://localhost:8088
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  routes:
    producer:
      path: /producer/**
      serviceId: SERVICE-PRODUCER
    consumer:
      path: /consumer/**
      serviceId: SERVICE-CONSUMER
eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
logging:
  path: logs/log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  jedis:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0

