server:
  port: 8088
eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: SERVER-ADMIN
  security:
    user:
      name: admin
      password: 1qaz2wsx