spring:
  application:
    name: MOM-PURCHASE
eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://192.168.3.138:9999/eureka
